// Mocks generated by Mockito 5.4.6 from annotations
// in poke_app/test/features/pokemon/presentation/providers/pokemon_list_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:poke_app/core/errors/failures.dart' as _i5;
import 'package:poke_app/features/pokemon/domain/entities/pokemon_detail_entity.dart'
    as _i7;
import 'package:poke_app/features/pokemon/domain/entities/pokemon_entity.dart'
    as _i6;
import 'package:poke_app/features/pokemon/domain/repositories/pokemon_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PokemonRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPokemonRepository extends _i1.Mock implements _i3.PokemonRepository {
  MockPokemonRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.PokemonEntity>>> getPokemonList({
    int? limit = 20,
    int? offset = 0,
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPokemonList,
          [],
          {
            #limit: limit,
            #offset: offset,
            #forceRefresh: forceRefresh,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.PokemonEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.PokemonEntity>>(
          this,
          Invocation.method(
            #getPokemonList,
            [],
            {
              #limit: limit,
              #offset: offset,
              #forceRefresh: forceRefresh,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.PokemonEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.PokemonDetailEntity>> getPokemonDetail(
          int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPokemonDetail,
          [id],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i7.PokemonDetailEntity>>.value(
                _FakeEither_0<_i5.Failure, _i7.PokemonDetailEntity>(
          this,
          Invocation.method(
            #getPokemonDetail,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i7.PokemonDetailEntity>>);

  @override
  _i4.Future<bool> hasCachedData() => (super.noSuchMethod(
        Invocation.method(
          #hasCachedData,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
