// Mocks generated by Mockito 5.4.6 from annotations
// in poke_app/test/features/pokemon/data/repositories/pokemon_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:poke_app/features/pokemon/data/datasources/pokemon_local_datasource.dart'
    as _i6;
import 'package:poke_app/features/pokemon/data/datasources/pokemon_remote_datasource.dart'
    as _i3;
import 'package:poke_app/features/pokemon/data/models/pokemo_detail_model.dart'
    as _i2;
import 'package:poke_app/features/pokemon/data/models/pokemon_isar_model.dart'
    as _i7;
import 'package:poke_app/features/pokemon/data/models/pokemon_model.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePokemonDetailModel_0 extends _i1.SmartFake
    implements _i2.PokemonDetailModel {
  _FakePokemonDetailModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PokemonRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPokemonRemoteDatasource extends _i1.Mock
    implements _i3.PokemonRemoteDatasource {
  MockPokemonRemoteDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.PokemonModel>> getPokemonList({
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPokemonList,
          [],
          {
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue:
            _i4.Future<List<_i5.PokemonModel>>.value(<_i5.PokemonModel>[]),
      ) as _i4.Future<List<_i5.PokemonModel>>);

  @override
  _i4.Future<_i2.PokemonDetailModel> getPokemonDetail(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPokemonDetail,
          [id],
        ),
        returnValue:
            _i4.Future<_i2.PokemonDetailModel>.value(_FakePokemonDetailModel_0(
          this,
          Invocation.method(
            #getPokemonDetail,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.PokemonDetailModel>);
}

/// A class which mocks [PokemonLocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPokemonLocalDatasource extends _i1.Mock
    implements _i6.PokemonLocalDatasource {
  MockPokemonLocalDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i7.PokemonIsarModel>?> getCachedPokemonList() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedPokemonList,
          [],
        ),
        returnValue: _i4.Future<List<_i7.PokemonIsarModel>?>.value(),
      ) as _i4.Future<List<_i7.PokemonIsarModel>?>);

  @override
  _i4.Future<_i7.PokemonDetailIsarModel?> getCachedPokemonDetail(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedPokemonDetail,
          [id],
        ),
        returnValue: _i4.Future<_i7.PokemonDetailIsarModel?>.value(),
      ) as _i4.Future<_i7.PokemonDetailIsarModel?>);

  @override
  _i4.Future<void> cachePokemonList(List<_i7.PokemonIsarModel>? pokemon) =>
      (super.noSuchMethod(
        Invocation.method(
          #cachePokemonList,
          [pokemon],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> cachePokemonDetail(_i7.PokemonDetailIsarModel? detail) =>
      (super.noSuchMethod(
        Invocation.method(
          #cachePokemonDetail,
          [detail],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> hasCachedData() => (super.noSuchMethod(
        Invocation.method(
          #hasCachedData,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
